### ISSUE TITLE
missing values in 'row.names' are not allowed ERROR

### ISSUE THREAD

**Issue by pgajer** [mbq/rFerns#9]
This

bor <- Boruta( y ~ X, doTrace=2, maxRuns = 1000, getImp=getImpFerns)

generate the error

run of importance source...
Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
  missing values in 'row.names' are not allowed

**Comment by pgajer** [comment]
This is a compressed directory with y and X used in the test example that generated the row.names error

[test.zip](https://github.com/mbq/rFerns/files/474436/test.zip)

**Comment by mbq** [comment]
The zip seems empty, but I can reproduce nevertheless. Investigating now.

As a fast fix, you can omit formula interface, i.e. call 
```r
bor <- Boruta(X, y, doTrace=2, maxRuns = 1000, getImp=getImpFerns)
```
this is also more efficient and takes less RAM.

**Comment by mbq** [comment]
Ok, the problem here is that your formula is incorrect; it says to analyse an information system with decision y and a single attribute X, but X is not a single vector so it makes no sense whatsoever. You probably wanted 
```r
Boruta(y~.,data=X)
```

Maybe it should have better error handling, but this is a separate topic.

**Comment by pgajer** [comment]
Thanks Miron,

Yes, indeed I messed up the syntax of the command. Thanks for pointing this
out !

I enjoyed reading your paper "Robustness of Random Forest-based gene
selection methods"

Can you clarify the last sentence of the fragment

"Next, all investigated methods were tested by the analysis of
post-selection error made by a classifier trained on a set reduced to the
selected genes. For this purpose, for each bootstrap iteration, a Random
Forest model composed of 50000 trees was trained on a set reduced to
objects belonging to the respective resampled set as well as features that
were selected by the given method; then, this model was tested on the
remaining objects that were not used in its training."

Did you use 10-fold cross-validation. That is randomly split your data (no
bootstrapped) into 10 ~equal parts and for each part, T_i, i=1, ..., 10, do
bootstrap of samples on the union, U_i, of the remaining 9 parts, identify
with Boruta selected genes. Train RF on U_i using selected genes and do
prediction on T_i.

Rozumiem ze jest pan polakiem i mowi pan po polsku. Ja mieszkam na stale w
Stanach ale teraz jestem w Polsce.

Dziekuje za pomoc !
:)
pawel

..

**Comment by mbq** [comment]
To może pogadamy przez maila?

**Comment by pgajer** [comment]
Czesc Miron (mam nadzieje ze nia masz nic na przeciwko jesli bedziemy
zwracac sie na ty)

Ja pracuje w The Institute for Genome Science http://www.igs.umaryland.edu/
ktory jest czescia szkoly medycznej University of Maryland. Z wyksztalcenia
jestem matematykiem (magisterka we Wroclawiu, PhD w Stanach) i robilem
kidys czysta matematyka. Ok 15 lat temu przerzucilem sie na bioinformatyke
co czynie po dzis dzien. Pracuje w labolatorium ktore zajmuje sie flora
bakteryjna vaginy kobiecej i roli tych bakterii w roznych stanach
chorobowych no i to do jakiego stopnia ona chroni kobiety (w zaleznosci od
jej struktury) przez chorobami.

Ostatnio glownie robie analizy statystyczne roznych projektow, ale
napisalem tez pare programow, z ktorych jeden przygotowuje do publikacji
PECAN
Mozesz wiecej zobaczyc co robimy tutaj http://ravel-lab.org/

Mamy pare projektow o wplywie flory bakteryjnej waginy na przedwczesne
porody. Oczywiscie chodzi o identyfikacje bakterii/genow, metabolicznych
scierzek(?) itp ktore sa w jakis sposob skorelowane z przedwczesnymi
porodami. Stad moje zainteresowanie metodami feature selection, szczegolnie
tymi ktore wybieraja all relevant features.

Zamierzam przetestowac Twoja metode oszacowania stabilnosci wyborow w
oparciu o 100 10-fold cross-validations i byc moze bootstraps na test sets.

Pozdrawiam serdecznie,
:)
pawel

**Comment by mbq** [comment]
Ok, ale proszę napisz do mnie bezpośrednio żeby nie off-topicować w tym issue. Adres masz na [CRANie](https://cran.r-project.org/web/packages/rFerns/index.html).
